### ISSUE TITLE
UTC issues with fluentd

### ISSUE THREAD

**Issue by audiolomb** [jfrog/log-analytics-splunk#73]
Hello there,

The configuration provided doesn't seem to be taking in account the time zone.
The events are sent to the Splunk HEC in UTC time, which creates issues with Splunk Searches.
In my timezone (PST), I have to search 7 hours in the future to get current events.

What changed do I need to make to the config file?

**Comment by benharosh** [comment]
Hi @audiolomb, can you confirm that your server/s run in local timezone (PST) and not UTC? 

Also, can you point to the section where you'd want a timezone support? If it's under a FluentD section with `@type splunk_hec`, it might be out of our control, since it's a Splunk FluentD plugin. That said, there might be other ways to adjust the event timezone before sending it to Splunk.

**Comment by benharosh** [comment]
@audiolomb  Hi, after receiving the same request internally via our support channels with some context, and looking into this issue again - it seems like what you ask can be achieved on the Splunk UI by adjusting the user time zone. Go to Splunk admin -> preferences -> Time Zone and choose PST TZ. Refresh the dashboard/search page and you are good to go. You might need to wait up to 1 minute for the change to take effect (and an extra refresh).

**Comment by audiolomb** [comment]
Hello Ben,

The UI is already set to PST.
So, no, this cannot be achieved by what you are suggesting.

Thank you,
Claudio
________________________________
